### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by xinli2008** [SusungHong/Self-Attention-Guidance#5]
nice job! And i try to use the SAG as follows:
`
from diffusers import  DiffusionPipeline,StableDiffusionSAGPipeline

pipe = StableDiffusionSAGPipeline.from_pretrained("/mnt/xxx/result_diffusers", torch_dtype=torch.float16, use_safetensors=True, variant="bf16")
pipe.to("cuda:0")

positive_prompt = 'sl_1234, man, long hair, wearing red sweater'

negative_prompt = 'text, worst quality'

image = pipe( positive_prompt,  negative_prompt=negative_prompt, num_inference_steps=50,  guidance_scale=7.5, 
        num_images_per_prompt=batch_size,
        sag_scale=1.0
    ).images
`
the error is :
File "demo.py", line 49, in <module>
    image = pipe(
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py", line 653, in __call__
    noise_pred = self.unet(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py", line 839, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

can you give me some advice? @SusungHong

**Comment by deltheil** [comment]
IIUC you are trying to use SAG with SDXL. But SDXL's UNet takes as input extra args (see [here](https://github.com/huggingface/diffusers/blob/e5168588864d72a4dca37e90318c6b11da0eaaf1/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L923)) and `StableDiffusionSAGPipeline` has not been expanded yet to support XL models (which is why you get this error: see [here](https://github.com/huggingface/diffusers/blob/e5168588864d72a4dca37e90318c6b11da0eaaf1/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_sag.py#L672-L677): the extra args are not passed to the UNet).

--

In the meanwhile you can test SAG with SDXL using [Refiners](https://github.com/finegrain-ai/refiners) (x) => **I put some instructions [here](https://gist.github.com/deltheil/9ba2c1840c3380e598698a16e0e09e3d?permalink_comment_id=4731152#gistcomment-4731152)**.

Hope that helps!

_(x): an open source, PyTorch-based framework made to easily train and run adapters on top of foundational models. See also #4_

**Comment by xinli2008** [comment]
thank you very much, i will try that.
